FROM amazoncorretto:11-al2-full

COPY build.gradle /build/
COPY gradlew /build/
COPY gradle/wrapper/ /build/gradle/wrapper
WORKDIR /build/

# Run clean to at least fetch gradle
RUN ./gradlew clean

# Fetch binaries
RUN ./gradlew downloadAll

COPY src /build/src
RUN ./gradlew build
